controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

jvis_base.login:
  path:     /home
  controller: 'App\Controller\HomeController:index'
  methods: GET

filter_list:
  path: /
  controller: App\Controller\Controller::index

new_filter:
  path: /filter/new
  controller: App\Controller\FilterController::new

new_filter_modal:
  path: /filter/new/modal
  controller: App\Controller\FilterController::newModal

edit_filter:
  path: /filter/edit/{id}
  controller: App\Controller\FilterController::edit


